/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnalysisGridSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnalysisGridSchemaTests
    {
        // TODO uncomment below to declare an instance variable for AnalysisGridSchema
        //private AnalysisGridSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnalysisGridSchema
            //instance = new AnalysisGridSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnalysisGridSchema
        /// </summary>
        [Test]
        public void AnalysisGridSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnalysisGridSchema
            //Assert.IsInstanceOfType<AnalysisGridSchema> (instance, "variable 'instance' is a AnalysisGridSchema");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'AnalysisPoints'
        /// </summary>
        [Test]
        public void AnalysisPointsTest()
        {
            // TODO unit test for the property 'AnalysisPoints'
        }
        /// <summary>
        /// Test the property 'WindowGroups'
        /// </summary>
        [Test]
        public void WindowGroupsTest()
        {
            // TODO unit test for the property 'WindowGroups'
        }

    }

}
