/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BSDFMaterialSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BSDFMaterialSchemaTests
    {
        // TODO uncomment below to declare an instance variable for BSDFMaterialSchema
        //private BSDFMaterialSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BSDFMaterialSchema
            //instance = new BSDFMaterialSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BSDFMaterialSchema
        /// </summary>
        [Test]
        public void BSDFMaterialSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BSDFMaterialSchema
            //Assert.IsInstanceOfType<BSDFMaterialSchema> (instance, "variable 'instance' is a BSDFMaterialSchema");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'XmlData'
        /// </summary>
        [Test]
        public void XmlDataTest()
        {
            // TODO unit test for the property 'XmlData'
        }
        /// <summary>
        /// Test the property 'UpOrientation'
        /// </summary>
        [Test]
        public void UpOrientationTest()
        {
            // TODO unit test for the property 'UpOrientation'
        }
        /// <summary>
        /// Test the property 'Thickness'
        /// </summary>
        [Test]
        public void ThicknessTest()
        {
            // TODO unit test for the property 'Thickness'
        }
        /// <summary>
        /// Test the property 'Modifier'
        /// </summary>
        [Test]
        public void ModifierTest()
        {
            // TODO unit test for the property 'Modifier'
        }

    }

}
