/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DataType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataTypeTests
    {
        // TODO uncomment below to declare an instance variable for DataType
        //private DataType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataType
            //instance = new DataType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataType
        /// </summary>
        [Test]
        public void DataTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataType
            //Assert.IsInstanceOfType<DataType> (instance, "variable 'instance' is a DataType");
        }


        /// <summary>
        /// Test the property 'Standard'
        /// </summary>
        [Test]
        public void StandardTest()
        {
            // TODO unit test for the property 'Standard'
        }
        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Test]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }

    }

}
