/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DaylightFactorGridBasedSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DaylightFactorGridBasedSchemaTests
    {
        // TODO uncomment below to declare an instance variable for DaylightFactorGridBasedSchema
        //private DaylightFactorGridBasedSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DaylightFactorGridBasedSchema
            //instance = new DaylightFactorGridBasedSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DaylightFactorGridBasedSchema
        /// </summary>
        [Test]
        public void DaylightFactorGridBasedSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DaylightFactorGridBasedSchema
            //Assert.IsInstanceOfType<DaylightFactorGridBasedSchema> (instance, "variable 'instance' is a DaylightFactorGridBasedSchema");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'AnalysisGrids'
        /// </summary>
        [Test]
        public void AnalysisGridsTest()
        {
            // TODO unit test for the property 'AnalysisGrids'
        }
        /// <summary>
        /// Test the property 'Surfaces'
        /// </summary>
        [Test]
        public void SurfacesTest()
        {
            // TODO unit test for the property 'Surfaces'
        }
        /// <summary>
        /// Test the property 'RadParameters'
        /// </summary>
        [Test]
        public void RadParametersTest()
        {
            // TODO unit test for the property 'RadParameters'
        }

    }

}
