/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20010
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20010Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20010
        //private InlineResponse20010 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20010
            //instance = new InlineResponse20010();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20010
        /// </summary>
        [Test]
        public void InlineResponse20010InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20010
            //Assert.IsInstanceOfType<InlineResponse20010> (instance, "variable 'instance' is a InlineResponse20010");
        }


        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Wea'
        /// </summary>
        [Test]
        public void WeaTest()
        {
            // TODO unit test for the property 'Wea'
        }

    }

}
