/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SurfaceStateSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SurfaceStateSchemaTests
    {
        // TODO uncomment below to declare an instance variable for SurfaceStateSchema
        //private SurfaceStateSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SurfaceStateSchema
            //instance = new SurfaceStateSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SurfaceStateSchema
        /// </summary>
        [Test]
        public void SurfaceStateSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SurfaceStateSchema
            //Assert.IsInstanceOfType<SurfaceStateSchema> (instance, "variable 'instance' is a SurfaceStateSchema");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SurfaceProperties'
        /// </summary>
        [Test]
        public void SurfacePropertiesTest()
        {
            // TODO unit test for the property 'SurfaceProperties'
        }

    }

}
