/**
 * Honeybee Server API
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HoneybeeServerApi);
  }
}(this, function(expect, HoneybeeServerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HoneybeeServerApi.SkyMtxSchema();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SkyMtxSchema', function() {
    it('should create an instance of SkyMtxSchema', function() {
      // uncomment below and update the code to test SkyMtxSchema
      //var instane = new HoneybeeServerApi.SkyMtxSchema();
      //expect(instance).to.be.a(HoneybeeServerApi.SkyMtxSchema);
    });

    it('should have the property wea (base name: "wea")', function() {
      // uncomment below and update the code to test the property wea
      //var instane = new HoneybeeServerApi.SkyMtxSchema();
      //expect(instance).to.be();
    });

    it('should have the property skyDensity (base name: "sky_density")', function() {
      // uncomment below and update the code to test the property skyDensity
      //var instane = new HoneybeeServerApi.SkyMtxSchema();
      //expect(instance).to.be();
    });

    it('should have the property north (base name: "north")', function() {
      // uncomment below and update the code to test the property north
      //var instane = new HoneybeeServerApi.SkyMtxSchema();
      //expect(instance).to.be();
    });

    it('should have the property hoys (base name: "hoys")', function() {
      // uncomment below and update the code to test the property hoys
      //var instane = new HoneybeeServerApi.SkyMtxSchema();
      //expect(instance).to.be();
    });

    it('should have the property mode (base name: "mode")', function() {
      // uncomment below and update the code to test the property mode
      //var instane = new HoneybeeServerApi.SkyMtxSchema();
      //expect(instance).to.be();
    });

    it('should have the property suffix (base name: "suffix")', function() {
      // uncomment below and update the code to test the property suffix
      //var instane = new HoneybeeServerApi.SkyMtxSchema();
      //expect(instance).to.be();
    });

  });

}));
