/**
 * Honeybee Server API
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PointSchema', 'model/SourceSchema', 'model/VectorSchema'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PointSchema'), require('./SourceSchema'), require('./VectorSchema'));
  } else {
    // Browser globals (root is window)
    if (!root.HoneybeeServerApi) {
      root.HoneybeeServerApi = {};
    }
    root.HoneybeeServerApi.AnalysisPointSchema = factory(root.HoneybeeServerApi.ApiClient, root.HoneybeeServerApi.PointSchema, root.HoneybeeServerApi.SourceSchema, root.HoneybeeServerApi.VectorSchema);
  }
}(this, function(ApiClient, PointSchema, SourceSchema, VectorSchema) {
  'use strict';




  /**
   * The AnalysisPointSchema model module.
   * @module model/AnalysisPointSchema
   * @version 0.0.0
   */

  /**
   * Constructs a new <code>AnalysisPointSchema</code>.
   * @alias module:model/AnalysisPointSchema
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>AnalysisPointSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnalysisPointSchema} obj Optional instance to populate.
   * @return {module:model/AnalysisPointSchema} The populated <code>AnalysisPointSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('location')) {
        obj['location'] = PointSchema.constructFromObject(data['location']);
      }
      if (data.hasOwnProperty('direction')) {
        obj['direction'] = VectorSchema.constructFromObject(data['direction']);
      }
      if (data.hasOwnProperty('values')) {
        obj['values'] = ApiClient.convertToType(data['values'], [SourceSchema]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PointSchema} location
   */
  exports.prototype['location'] = undefined;
  /**
   * @member {module:model/VectorSchema} direction
   */
  exports.prototype['direction'] = undefined;
  /**
   * @member {Array.<module:model/SourceSchema>} values
   */
  exports.prototype['values'] = undefined;



  return exports;
}));


