/**
 * Honeybee Server API
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AnalysisSurfaceSchema'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AnalysisSurfaceSchema'));
  } else {
    // Browser globals (root is window)
    if (!root.HoneybeeServerApi) {
      root.HoneybeeServerApi = {};
    }
    root.HoneybeeServerApi.HBSurfaceSchema = factory(root.HoneybeeServerApi.ApiClient, root.HoneybeeServerApi.AnalysisSurfaceSchema);
  }
}(this, function(ApiClient, AnalysisSurfaceSchema) {
  'use strict';




  /**
   * The HBSurfaceSchema model module.
   * @module model/HBSurfaceSchema
   * @version 0.0.0
   */

  /**
   * Constructs a new <code>HBSurfaceSchema</code>.
   * @alias module:model/HBSurfaceSchema
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>HBSurfaceSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HBSurfaceSchema} obj Optional instance to populate.
   * @return {module:model/HBSurfaceSchema} The populated <code>HBSurfaceSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('parent_surface')) {
        obj['parent_surface'] = AnalysisSurfaceSchema.constructFromObject(data['parent_surface']);
      }
      if (data.hasOwnProperty('child_surfaces')) {
        obj['child_surfaces'] = ApiClient.convertToType(data['child_surfaces'], [AnalysisSurfaceSchema]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AnalysisSurfaceSchema} parent_surface
   */
  exports.prototype['parent_surface'] = undefined;
  /**
   * @member {Array.<module:model/AnalysisSurfaceSchema>} child_surfaces
   */
  exports.prototype['child_surfaces'] = undefined;



  return exports;
}));


