/**
 * Honeybee Server API
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HoySchemaHoy'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HoySchemaHoy'));
  } else {
    // Browser globals (root is window)
    if (!root.HoneybeeServerApi) {
      root.HoneybeeServerApi = {};
    }
    root.HoneybeeServerApi.HoySchema = factory(root.HoneybeeServerApi.ApiClient, root.HoneybeeServerApi.HoySchemaHoy);
  }
}(this, function(ApiClient, HoySchemaHoy) {
  'use strict';




  /**
   * The HoySchema model module.
   * @module model/HoySchema
   * @version 0.0.0
   */

  /**
   * Constructs a new <code>HoySchema</code>.
   * @alias module:model/HoySchema
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>HoySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HoySchema} obj Optional instance to populate.
   * @return {module:model/HoySchema} The populated <code>HoySchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('hoy_id')) {
        obj['hoy_id'] = ApiClient.convertToType(data['hoy_id'], 'Number');
      }
      if (data.hasOwnProperty('hoy')) {
        obj['hoy'] = HoySchemaHoy.constructFromObject(data['hoy']);
      }
    }
    return obj;
  }

  /**
   * The hour of the year for a given set of results values
   * @member {Number} hoy_id
   */
  exports.prototype['hoy_id'] = undefined;
  /**
   * @member {module:model/HoySchemaHoy} hoy
   */
  exports.prototype['hoy'] = undefined;



  return exports;
}));


