/*
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AnalysisSurfaceSchemaRadProperties struct {

	Uuid string `json:"uuid,omitempty"`

	Material *MaterialSchema `json:"material,omitempty"`
}
