# coding: utf-8

"""
    Honeybee Server API

    A sample API definition for a honeybee server  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HoySchemaHoy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'direct_value': 'float',
        'indirect_value': 'float'
    }

    attribute_map = {
        'direct_value': 'direct_value',
        'indirect_value': 'indirect_value'
    }

    def __init__(self, direct_value=None, indirect_value=None):  # noqa: E501
        """HoySchemaHoy - a model defined in Swagger"""  # noqa: E501

        self._direct_value = None
        self._indirect_value = None
        self.discriminator = None

        if direct_value is not None:
            self.direct_value = direct_value
        if indirect_value is not None:
            self.indirect_value = indirect_value

    @property
    def direct_value(self):
        """Gets the direct_value of this HoySchemaHoy.  # noqa: E501


        :return: The direct_value of this HoySchemaHoy.  # noqa: E501
        :rtype: float
        """
        return self._direct_value

    @direct_value.setter
    def direct_value(self, direct_value):
        """Sets the direct_value of this HoySchemaHoy.


        :param direct_value: The direct_value of this HoySchemaHoy.  # noqa: E501
        :type: float
        """

        self._direct_value = direct_value

    @property
    def indirect_value(self):
        """Gets the indirect_value of this HoySchemaHoy.  # noqa: E501


        :return: The indirect_value of this HoySchemaHoy.  # noqa: E501
        :rtype: float
        """
        return self._indirect_value

    @indirect_value.setter
    def indirect_value(self, indirect_value):
        """Sets the indirect_value of this HoySchemaHoy.


        :param indirect_value: The indirect_value of this HoySchemaHoy.  # noqa: E501
        :type: float
        """

        self._indirect_value = indirect_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HoySchemaHoy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
