/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EpwSchema
    /// </summary>
    [DataContract]
    public partial class EpwSchema :  IEquatable<EpwSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EpwSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EpwSchema() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EpwSchema" /> class.
        /// </summary>
        /// <param name="Header">Header (required).</param>
        /// <param name="Location">Location (required).</param>
        /// <param name="Data">Data (required).</param>
        public EpwSchema(List<string> Header = default(List<string>), EpwLocationSchema Location = default(EpwLocationSchema), List<DataCollectionSchema> Data = default(List<DataCollectionSchema>))
        {
            // to ensure "Header" is required (not null)
            if (Header == null)
            {
                throw new InvalidDataException("Header is a required property for EpwSchema and cannot be null");
            }
            else
            {
                this.Header = Header;
            }
            // to ensure "Location" is required (not null)
            if (Location == null)
            {
                throw new InvalidDataException("Location is a required property for EpwSchema and cannot be null");
            }
            else
            {
                this.Location = Location;
            }
            // to ensure "Data" is required (not null)
            if (Data == null)
            {
                throw new InvalidDataException("Data is a required property for EpwSchema and cannot be null");
            }
            else
            {
                this.Data = Data;
            }
        }
        
        /// <summary>
        /// Gets or Sets Header
        /// </summary>
        [DataMember(Name="header", EmitDefaultValue=false)]
        public List<string> Header { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location", EmitDefaultValue=false)]
        public EpwLocationSchema Location { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="data", EmitDefaultValue=false)]
        public List<DataCollectionSchema> Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EpwSchema {\n");
            sb.Append("  Header: ").Append(Header).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EpwSchema);
        }

        /// <summary>
        /// Returns true if EpwSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of EpwSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EpwSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Header == input.Header ||
                    this.Header != null &&
                    this.Header.SequenceEqual(input.Header)
                ) && 
                (
                    this.Location == input.Location ||
                    (this.Location != null &&
                    this.Location.Equals(input.Location))
                ) && 
                (
                    this.Data == input.Data ||
                    this.Data != null &&
                    this.Data.SequenceEqual(input.Data)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Header != null)
                    hashCode = hashCode * 59 + this.Header.GetHashCode();
                if (this.Location != null)
                    hashCode = hashCode * 59 + this.Location.GetHashCode();
                if (this.Data != null)
                    hashCode = hashCode * 59 + this.Data.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
