/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WeaSchema
    /// </summary>
    [DataContract]
    public partial class WeaSchema :  IEquatable<WeaSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WeaSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WeaSchema() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WeaSchema" /> class.
        /// </summary>
        /// <param name="Header">Header (required).</param>
        /// <param name="Location">Location (required).</param>
        /// <param name="DirectNormalRadiation">DirectNormalRadiation.</param>
        /// <param name="DiffuseHorizontalRadiation">DiffuseHorizontalRadiation.</param>
        public WeaSchema(List<string> Header = default(List<string>), EpwLocationSchema Location = default(EpwLocationSchema), DataCollectionSchema DirectNormalRadiation = default(DataCollectionSchema), DataCollectionSchema DiffuseHorizontalRadiation = default(DataCollectionSchema))
        {
            // to ensure "Header" is required (not null)
            if (Header == null)
            {
                throw new InvalidDataException("Header is a required property for WeaSchema and cannot be null");
            }
            else
            {
                this.Header = Header;
            }
            // to ensure "Location" is required (not null)
            if (Location == null)
            {
                throw new InvalidDataException("Location is a required property for WeaSchema and cannot be null");
            }
            else
            {
                this.Location = Location;
            }
            this.DirectNormalRadiation = DirectNormalRadiation;
            this.DiffuseHorizontalRadiation = DiffuseHorizontalRadiation;
        }
        
        /// <summary>
        /// Gets or Sets Header
        /// </summary>
        [DataMember(Name="header", EmitDefaultValue=false)]
        public List<string> Header { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location", EmitDefaultValue=false)]
        public EpwLocationSchema Location { get; set; }

        /// <summary>
        /// Gets or Sets DirectNormalRadiation
        /// </summary>
        [DataMember(Name="direct_normal_radiation", EmitDefaultValue=false)]
        public DataCollectionSchema DirectNormalRadiation { get; set; }

        /// <summary>
        /// Gets or Sets DiffuseHorizontalRadiation
        /// </summary>
        [DataMember(Name="diffuse_horizontal_radiation", EmitDefaultValue=false)]
        public DataCollectionSchema DiffuseHorizontalRadiation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WeaSchema {\n");
            sb.Append("  Header: ").Append(Header).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  DirectNormalRadiation: ").Append(DirectNormalRadiation).Append("\n");
            sb.Append("  DiffuseHorizontalRadiation: ").Append(DiffuseHorizontalRadiation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WeaSchema);
        }

        /// <summary>
        /// Returns true if WeaSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of WeaSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WeaSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Header == input.Header ||
                    this.Header != null &&
                    this.Header.SequenceEqual(input.Header)
                ) && 
                (
                    this.Location == input.Location ||
                    (this.Location != null &&
                    this.Location.Equals(input.Location))
                ) && 
                (
                    this.DirectNormalRadiation == input.DirectNormalRadiation ||
                    (this.DirectNormalRadiation != null &&
                    this.DirectNormalRadiation.Equals(input.DirectNormalRadiation))
                ) && 
                (
                    this.DiffuseHorizontalRadiation == input.DiffuseHorizontalRadiation ||
                    (this.DiffuseHorizontalRadiation != null &&
                    this.DiffuseHorizontalRadiation.Equals(input.DiffuseHorizontalRadiation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Header != null)
                    hashCode = hashCode * 59 + this.Header.GetHashCode();
                if (this.Location != null)
                    hashCode = hashCode * 59 + this.Location.GetHashCode();
                if (this.DirectNormalRadiation != null)
                    hashCode = hashCode * 59 + this.DirectNormalRadiation.GetHashCode();
                if (this.DiffuseHorizontalRadiation != null)
                    hashCode = hashCode * 59 + this.DiffuseHorizontalRadiation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
