/**
 * Honeybee Server API
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EpwSchema', 'model/InlineResponse2002', 'model/InlineResponse2003', 'model/InlineResponse204', 'model/InlineResponse400'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/EpwSchema'), require('../model/InlineResponse2002'), require('../model/InlineResponse2003'), require('../model/InlineResponse204'), require('../model/InlineResponse400'));
  } else {
    // Browser globals (root is window)
    if (!root.HoneybeeServerApi) {
      root.HoneybeeServerApi = {};
    }
    root.HoneybeeServerApi.EPWApi = factory(root.HoneybeeServerApi.ApiClient, root.HoneybeeServerApi.EpwSchema, root.HoneybeeServerApi.InlineResponse2002, root.HoneybeeServerApi.InlineResponse2003, root.HoneybeeServerApi.InlineResponse204, root.HoneybeeServerApi.InlineResponse400);
  }
}(this, function(ApiClient, EpwSchema, InlineResponse2002, InlineResponse2003, InlineResponse204, InlineResponse400) {
  'use strict';

  /**
   * EPW service.
   * @module api/EPWApi
   * @version 0.0.0
   */

  /**
   * Constructs a new EPWApi. 
   * @alias module:api/EPWApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the epwGet operation.
     * @callback module:api/EPWApi~epwGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of EPW objects
     * Retrieves a list of epw objects for a given filter.
     * @param {Object} opts Optional parameters
     * @param {String} opts.country The countyr the EPW is from
     * @param {module:api/EPWApi~epwGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2002}
     */
    this.epwGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'country': opts['country'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/epw', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the epwPost operation.
     * @callback module:api/EPWApi~epwPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse204} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new epw file
     * Adds a new epw file to the list
     * @param {module:model/EpwSchema} epw The location of the epw.
     * @param {module:api/EPWApi~epwPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse204}
     */
    this.epwPost = function(epw, callback) {
      var postBody = epw;

      // verify the required parameter 'epw' is set
      if (epw === undefined || epw === null) {
        throw new Error("Missing the required parameter 'epw' when calling epwPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = InlineResponse204;

      return this.apiClient.callApi(
        '/epw', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the epwUuidDelete operation.
     * @callback module:api/EPWApi~epwUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an existing epw file
     * Delete an epw file in the database specifying the uuid of the file
     * @param {String} uuid The unique identifier of the epw.
     * @param {module:api/EPWApi~epwUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.epwUuidDelete = function(uuid, callback) {
      var postBody = null;

      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling epwUuidDelete");
      }


      var pathParams = {
        'uuid': uuid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/epw/{uuid}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the epwUuidGet operation.
     * @callback module:api/EPWApi~epwUuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a specific epw file
     * Returns a single epw file
     * @param {String} uuid The unique identifier of the epw.
     * @param {module:api/EPWApi~epwUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    this.epwUuidGet = function(uuid, callback) {
      var postBody = null;

      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling epwUuidGet");
      }


      var pathParams = {
        'uuid': uuid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/epw/{uuid}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the epwUuidPut operation.
     * @callback module:api/EPWApi~epwUuidPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modify an existing epw file
     * Modifies any parameter (except uuid) of an epw file by completely replacing the EPW file. A finer grain method can be set up later.
     * @param {String} uuid The unique identifier of the epw.
     * @param {module:model/EpwSchema} epw The location of the epw.
     * @param {module:api/EPWApi~epwUuidPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.epwUuidPut = function(uuid, epw, callback) {
      var postBody = epw;

      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling epwUuidPut");
      }

      // verify the required parameter 'epw' is set
      if (epw === undefined || epw === null) {
        throw new Error("Missing the required parameter 'epw' when calling epwUuidPut");
      }


      var pathParams = {
        'uuid': uuid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/epw/{uuid}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
