/**
 * Honeybee Server API
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2004', 'model/InlineResponse2005', 'model/InlineResponse400'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse2004'), require('../model/InlineResponse2005'), require('../model/InlineResponse400'));
  } else {
    // Browser globals (root is window)
    if (!root.HoneybeeServerApi) {
      root.HoneybeeServerApi = {};
    }
    root.HoneybeeServerApi.GetAndDeleteMaterialsApi = factory(root.HoneybeeServerApi.ApiClient, root.HoneybeeServerApi.InlineResponse2004, root.HoneybeeServerApi.InlineResponse2005, root.HoneybeeServerApi.InlineResponse400);
  }
}(this, function(ApiClient, InlineResponse2004, InlineResponse2005, InlineResponse400) {
  'use strict';

  /**
   * GetAndDeleteMaterials service.
   * @module api/GetAndDeleteMaterialsApi
   * @version 0.0.0
   */

  /**
   * Constructs a new GetAndDeleteMaterialsApi. 
   * @alias module:api/GetAndDeleteMaterialsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the materialGet operation.
     * @callback module:api/GetAndDeleteMaterialsApi~materialGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2004} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of material objects
     * Retrieves a list of material uuids for a given filter.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.materialType The type of the material to be queried
     * @param {Number} opts.rgbTransmittance The RGB average transmittance value (will only return translucent material)
     * @param {Number} opts.rgbReflectance The RGB average reflectance value (will only return opaque material)
     * @param {module:api/GetAndDeleteMaterialsApi~materialGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2004}
     */
    this.materialGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'material_type': opts['materialType'],
        'rgb_transmittance': opts['rgbTransmittance'],
        'rgb_reflectance': opts['rgbReflectance'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = InlineResponse2004;

      return this.apiClient.callApi(
        '/material', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the materialUuidDelete operation.
     * @callback module:api/GetAndDeleteMaterialsApi~materialUuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an existing material file
     * Delete an material file in the database specifying the uuid of the file
     * @param {String} uuid The unique identifier of the material.
     * @param {module:api/GetAndDeleteMaterialsApi~materialUuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.materialUuidDelete = function(uuid, callback) {
      var postBody = null;

      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling materialUuidDelete");
      }


      var pathParams = {
        'uuid': uuid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/material/{uuid}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the materialUuidGet operation.
     * @callback module:api/GetAndDeleteMaterialsApi~materialUuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2005} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a specific material object
     * Returns a single material object
     * @param {String} uuid The unique identifier of the material.
     * @param {module:api/GetAndDeleteMaterialsApi~materialUuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2005}
     */
    this.materialUuidGet = function(uuid, callback) {
      var postBody = null;

      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling materialUuidGet");
      }


      var pathParams = {
        'uuid': uuid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = InlineResponse2005;

      return this.apiClient.callApi(
        '/material/{uuid}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
