/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHoneybeeSurfaceApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get a list of hbsurface objects
        /// </summary>
        /// <remarks>
        /// Retrieves a list of HoneyBee Surface objects for a given filter.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="surfaceType">The type of the surface to be queried (optional)</param>
        /// <param name="surfaceMaterial">retrieve surfaces based on the name of their main material definiton (not materials in a given surface state) (optional)</param>
        /// <param name="surfaceState">retrieve a surface using the name of a given state it contains (optional)</param>
        /// <returns>InlineResponse2007</returns>
        InlineResponse2007 HbsurfaceGet (string surfaceType = null, string surfaceMaterial = null, string surfaceState = null);

        /// <summary>
        /// Get a list of hbsurface objects
        /// </summary>
        /// <remarks>
        /// Retrieves a list of HoneyBee Surface objects for a given filter.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="surfaceType">The type of the surface to be queried (optional)</param>
        /// <param name="surfaceMaterial">retrieve surfaces based on the name of their main material definiton (not materials in a given surface state) (optional)</param>
        /// <param name="surfaceState">retrieve a surface using the name of a given state it contains (optional)</param>
        /// <returns>ApiResponse of InlineResponse2007</returns>
        ApiResponse<InlineResponse2007> HbsurfaceGetWithHttpInfo (string surfaceType = null, string surfaceMaterial = null, string surfaceState = null);
        /// <summary>
        /// Create a new hbsurface object
        /// </summary>
        /// <remarks>
        /// Adds a new hbsurface object to the list
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hbsurface">A hbsurface JSON object</param>
        /// <returns>InlineResponse204</returns>
        InlineResponse204 HbsurfacePost (HBSurfaceSchema hbsurface);

        /// <summary>
        /// Create a new hbsurface object
        /// </summary>
        /// <remarks>
        /// Adds a new hbsurface object to the list
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hbsurface">A hbsurface JSON object</param>
        /// <returns>ApiResponse of InlineResponse204</returns>
        ApiResponse<InlineResponse204> HbsurfacePostWithHttpInfo (HBSurfaceSchema hbsurface);
        /// <summary>
        /// Delete an existing hbsurface object
        /// </summary>
        /// <remarks>
        /// Delete an hbsurface object in the database specifying the uuid of the object
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns></returns>
        void HbsurfaceUuidDelete (string uuid);

        /// <summary>
        /// Delete an existing hbsurface object
        /// </summary>
        /// <remarks>
        /// Delete an hbsurface object in the database specifying the uuid of the object
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> HbsurfaceUuidDeleteWithHttpInfo (string uuid);
        /// <summary>
        /// Get a specific hbsurface object
        /// </summary>
        /// <remarks>
        /// Returns a single hbsurface object
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>InlineResponse2008</returns>
        InlineResponse2008 HbsurfaceUuidGet (string uuid);

        /// <summary>
        /// Get a specific hbsurface object
        /// </summary>
        /// <remarks>
        /// Returns a single hbsurface object
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>ApiResponse of InlineResponse2008</returns>
        ApiResponse<InlineResponse2008> HbsurfaceUuidGetWithHttpInfo (string uuid);
        /// <summary>
        /// Modify an existing hbsurface object
        /// </summary>
        /// <remarks>
        /// Modifies any parameter (except uuid) of an hbsurface object by completely replacing the definition object. A finer grain method can be set up later.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <param name="hbsurface">A hbsurface JSON objectr with a uuid key.</param>
        /// <returns></returns>
        void HbsurfaceUuidPut (string uuid, HBSurfaceSchema hbsurface);

        /// <summary>
        /// Modify an existing hbsurface object
        /// </summary>
        /// <remarks>
        /// Modifies any parameter (except uuid) of an hbsurface object by completely replacing the definition object. A finer grain method can be set up later.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <param name="hbsurface">A hbsurface JSON objectr with a uuid key.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> HbsurfaceUuidPutWithHttpInfo (string uuid, HBSurfaceSchema hbsurface);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get a list of hbsurface objects
        /// </summary>
        /// <remarks>
        /// Retrieves a list of HoneyBee Surface objects for a given filter.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="surfaceType">The type of the surface to be queried (optional)</param>
        /// <param name="surfaceMaterial">retrieve surfaces based on the name of their main material definiton (not materials in a given surface state) (optional)</param>
        /// <param name="surfaceState">retrieve a surface using the name of a given state it contains (optional)</param>
        /// <returns>Task of InlineResponse2007</returns>
        System.Threading.Tasks.Task<InlineResponse2007> HbsurfaceGetAsync (string surfaceType = null, string surfaceMaterial = null, string surfaceState = null);

        /// <summary>
        /// Get a list of hbsurface objects
        /// </summary>
        /// <remarks>
        /// Retrieves a list of HoneyBee Surface objects for a given filter.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="surfaceType">The type of the surface to be queried (optional)</param>
        /// <param name="surfaceMaterial">retrieve surfaces based on the name of their main material definiton (not materials in a given surface state) (optional)</param>
        /// <param name="surfaceState">retrieve a surface using the name of a given state it contains (optional)</param>
        /// <returns>Task of ApiResponse (InlineResponse2007)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse2007>> HbsurfaceGetAsyncWithHttpInfo (string surfaceType = null, string surfaceMaterial = null, string surfaceState = null);
        /// <summary>
        /// Create a new hbsurface object
        /// </summary>
        /// <remarks>
        /// Adds a new hbsurface object to the list
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hbsurface">A hbsurface JSON object</param>
        /// <returns>Task of InlineResponse204</returns>
        System.Threading.Tasks.Task<InlineResponse204> HbsurfacePostAsync (HBSurfaceSchema hbsurface);

        /// <summary>
        /// Create a new hbsurface object
        /// </summary>
        /// <remarks>
        /// Adds a new hbsurface object to the list
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hbsurface">A hbsurface JSON object</param>
        /// <returns>Task of ApiResponse (InlineResponse204)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse204>> HbsurfacePostAsyncWithHttpInfo (HBSurfaceSchema hbsurface);
        /// <summary>
        /// Delete an existing hbsurface object
        /// </summary>
        /// <remarks>
        /// Delete an hbsurface object in the database specifying the uuid of the object
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task HbsurfaceUuidDeleteAsync (string uuid);

        /// <summary>
        /// Delete an existing hbsurface object
        /// </summary>
        /// <remarks>
        /// Delete an hbsurface object in the database specifying the uuid of the object
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> HbsurfaceUuidDeleteAsyncWithHttpInfo (string uuid);
        /// <summary>
        /// Get a specific hbsurface object
        /// </summary>
        /// <remarks>
        /// Returns a single hbsurface object
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>Task of InlineResponse2008</returns>
        System.Threading.Tasks.Task<InlineResponse2008> HbsurfaceUuidGetAsync (string uuid);

        /// <summary>
        /// Get a specific hbsurface object
        /// </summary>
        /// <remarks>
        /// Returns a single hbsurface object
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>Task of ApiResponse (InlineResponse2008)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse2008>> HbsurfaceUuidGetAsyncWithHttpInfo (string uuid);
        /// <summary>
        /// Modify an existing hbsurface object
        /// </summary>
        /// <remarks>
        /// Modifies any parameter (except uuid) of an hbsurface object by completely replacing the definition object. A finer grain method can be set up later.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <param name="hbsurface">A hbsurface JSON objectr with a uuid key.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task HbsurfaceUuidPutAsync (string uuid, HBSurfaceSchema hbsurface);

        /// <summary>
        /// Modify an existing hbsurface object
        /// </summary>
        /// <remarks>
        /// Modifies any parameter (except uuid) of an hbsurface object by completely replacing the definition object. A finer grain method can be set up later.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <param name="hbsurface">A hbsurface JSON objectr with a uuid key.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> HbsurfaceUuidPutAsyncWithHttpInfo (string uuid, HBSurfaceSchema hbsurface);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class HoneybeeSurfaceApi : IHoneybeeSurfaceApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="HoneybeeSurfaceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public HoneybeeSurfaceApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HoneybeeSurfaceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public HoneybeeSurfaceApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get a list of hbsurface objects Retrieves a list of HoneyBee Surface objects for a given filter.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="surfaceType">The type of the surface to be queried (optional)</param>
        /// <param name="surfaceMaterial">retrieve surfaces based on the name of their main material definiton (not materials in a given surface state) (optional)</param>
        /// <param name="surfaceState">retrieve a surface using the name of a given state it contains (optional)</param>
        /// <returns>InlineResponse2007</returns>
        public InlineResponse2007 HbsurfaceGet (string surfaceType = null, string surfaceMaterial = null, string surfaceState = null)
        {
             ApiResponse<InlineResponse2007> localVarResponse = HbsurfaceGetWithHttpInfo(surfaceType, surfaceMaterial, surfaceState);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a list of hbsurface objects Retrieves a list of HoneyBee Surface objects for a given filter.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="surfaceType">The type of the surface to be queried (optional)</param>
        /// <param name="surfaceMaterial">retrieve surfaces based on the name of their main material definiton (not materials in a given surface state) (optional)</param>
        /// <param name="surfaceState">retrieve a surface using the name of a given state it contains (optional)</param>
        /// <returns>ApiResponse of InlineResponse2007</returns>
        public ApiResponse< InlineResponse2007 > HbsurfaceGetWithHttpInfo (string surfaceType = null, string surfaceMaterial = null, string surfaceState = null)
        {

            var localVarPath = "/hbsurface";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (surfaceType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "surface_type", surfaceType)); // query parameter
            if (surfaceMaterial != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "surface_material", surfaceMaterial)); // query parameter
            if (surfaceState != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "surface_state", surfaceState)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfaceGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2007>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse2007) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2007)));
        }

        /// <summary>
        /// Get a list of hbsurface objects Retrieves a list of HoneyBee Surface objects for a given filter.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="surfaceType">The type of the surface to be queried (optional)</param>
        /// <param name="surfaceMaterial">retrieve surfaces based on the name of their main material definiton (not materials in a given surface state) (optional)</param>
        /// <param name="surfaceState">retrieve a surface using the name of a given state it contains (optional)</param>
        /// <returns>Task of InlineResponse2007</returns>
        public async System.Threading.Tasks.Task<InlineResponse2007> HbsurfaceGetAsync (string surfaceType = null, string surfaceMaterial = null, string surfaceState = null)
        {
             ApiResponse<InlineResponse2007> localVarResponse = await HbsurfaceGetAsyncWithHttpInfo(surfaceType, surfaceMaterial, surfaceState);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a list of hbsurface objects Retrieves a list of HoneyBee Surface objects for a given filter.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="surfaceType">The type of the surface to be queried (optional)</param>
        /// <param name="surfaceMaterial">retrieve surfaces based on the name of their main material definiton (not materials in a given surface state) (optional)</param>
        /// <param name="surfaceState">retrieve a surface using the name of a given state it contains (optional)</param>
        /// <returns>Task of ApiResponse (InlineResponse2007)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse2007>> HbsurfaceGetAsyncWithHttpInfo (string surfaceType = null, string surfaceMaterial = null, string surfaceState = null)
        {

            var localVarPath = "/hbsurface";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (surfaceType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "surface_type", surfaceType)); // query parameter
            if (surfaceMaterial != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "surface_material", surfaceMaterial)); // query parameter
            if (surfaceState != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "surface_state", surfaceState)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfaceGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2007>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse2007) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2007)));
        }

        /// <summary>
        /// Create a new hbsurface object Adds a new hbsurface object to the list
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hbsurface">A hbsurface JSON object</param>
        /// <returns>InlineResponse204</returns>
        public InlineResponse204 HbsurfacePost (HBSurfaceSchema hbsurface)
        {
             ApiResponse<InlineResponse204> localVarResponse = HbsurfacePostWithHttpInfo(hbsurface);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new hbsurface object Adds a new hbsurface object to the list
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hbsurface">A hbsurface JSON object</param>
        /// <returns>ApiResponse of InlineResponse204</returns>
        public ApiResponse< InlineResponse204 > HbsurfacePostWithHttpInfo (HBSurfaceSchema hbsurface)
        {
            // verify the required parameter 'hbsurface' is set
            if (hbsurface == null)
                throw new ApiException(400, "Missing required parameter 'hbsurface' when calling HoneybeeSurfaceApi->HbsurfacePost");

            var localVarPath = "/hbsurface";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (hbsurface != null && hbsurface.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(hbsurface); // http body (model) parameter
            }
            else
            {
                localVarPostBody = hbsurface; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfacePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse204>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse204) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse204)));
        }

        /// <summary>
        /// Create a new hbsurface object Adds a new hbsurface object to the list
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hbsurface">A hbsurface JSON object</param>
        /// <returns>Task of InlineResponse204</returns>
        public async System.Threading.Tasks.Task<InlineResponse204> HbsurfacePostAsync (HBSurfaceSchema hbsurface)
        {
             ApiResponse<InlineResponse204> localVarResponse = await HbsurfacePostAsyncWithHttpInfo(hbsurface);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a new hbsurface object Adds a new hbsurface object to the list
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hbsurface">A hbsurface JSON object</param>
        /// <returns>Task of ApiResponse (InlineResponse204)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse204>> HbsurfacePostAsyncWithHttpInfo (HBSurfaceSchema hbsurface)
        {
            // verify the required parameter 'hbsurface' is set
            if (hbsurface == null)
                throw new ApiException(400, "Missing required parameter 'hbsurface' when calling HoneybeeSurfaceApi->HbsurfacePost");

            var localVarPath = "/hbsurface";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (hbsurface != null && hbsurface.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(hbsurface); // http body (model) parameter
            }
            else
            {
                localVarPostBody = hbsurface; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfacePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse204>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse204) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse204)));
        }

        /// <summary>
        /// Delete an existing hbsurface object Delete an hbsurface object in the database specifying the uuid of the object
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns></returns>
        public void HbsurfaceUuidDelete (string uuid)
        {
             HbsurfaceUuidDeleteWithHttpInfo(uuid);
        }

        /// <summary>
        /// Delete an existing hbsurface object Delete an hbsurface object in the database specifying the uuid of the object
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> HbsurfaceUuidDeleteWithHttpInfo (string uuid)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling HoneybeeSurfaceApi->HbsurfaceUuidDelete");

            var localVarPath = "/hbsurface/{uuid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", Configuration.ApiClient.ParameterToString(uuid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfaceUuidDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete an existing hbsurface object Delete an hbsurface object in the database specifying the uuid of the object
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task HbsurfaceUuidDeleteAsync (string uuid)
        {
             await HbsurfaceUuidDeleteAsyncWithHttpInfo(uuid);

        }

        /// <summary>
        /// Delete an existing hbsurface object Delete an hbsurface object in the database specifying the uuid of the object
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> HbsurfaceUuidDeleteAsyncWithHttpInfo (string uuid)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling HoneybeeSurfaceApi->HbsurfaceUuidDelete");

            var localVarPath = "/hbsurface/{uuid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", Configuration.ApiClient.ParameterToString(uuid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfaceUuidDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get a specific hbsurface object Returns a single hbsurface object
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>InlineResponse2008</returns>
        public InlineResponse2008 HbsurfaceUuidGet (string uuid)
        {
             ApiResponse<InlineResponse2008> localVarResponse = HbsurfaceUuidGetWithHttpInfo(uuid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a specific hbsurface object Returns a single hbsurface object
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>ApiResponse of InlineResponse2008</returns>
        public ApiResponse< InlineResponse2008 > HbsurfaceUuidGetWithHttpInfo (string uuid)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling HoneybeeSurfaceApi->HbsurfaceUuidGet");

            var localVarPath = "/hbsurface/{uuid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", Configuration.ApiClient.ParameterToString(uuid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfaceUuidGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2008>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse2008) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2008)));
        }

        /// <summary>
        /// Get a specific hbsurface object Returns a single hbsurface object
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>Task of InlineResponse2008</returns>
        public async System.Threading.Tasks.Task<InlineResponse2008> HbsurfaceUuidGetAsync (string uuid)
        {
             ApiResponse<InlineResponse2008> localVarResponse = await HbsurfaceUuidGetAsyncWithHttpInfo(uuid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a specific hbsurface object Returns a single hbsurface object
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <returns>Task of ApiResponse (InlineResponse2008)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse2008>> HbsurfaceUuidGetAsyncWithHttpInfo (string uuid)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling HoneybeeSurfaceApi->HbsurfaceUuidGet");

            var localVarPath = "/hbsurface/{uuid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", Configuration.ApiClient.ParameterToString(uuid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfaceUuidGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2008>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse2008) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2008)));
        }

        /// <summary>
        /// Modify an existing hbsurface object Modifies any parameter (except uuid) of an hbsurface object by completely replacing the definition object. A finer grain method can be set up later.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <param name="hbsurface">A hbsurface JSON objectr with a uuid key.</param>
        /// <returns></returns>
        public void HbsurfaceUuidPut (string uuid, HBSurfaceSchema hbsurface)
        {
             HbsurfaceUuidPutWithHttpInfo(uuid, hbsurface);
        }

        /// <summary>
        /// Modify an existing hbsurface object Modifies any parameter (except uuid) of an hbsurface object by completely replacing the definition object. A finer grain method can be set up later.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <param name="hbsurface">A hbsurface JSON objectr with a uuid key.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> HbsurfaceUuidPutWithHttpInfo (string uuid, HBSurfaceSchema hbsurface)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling HoneybeeSurfaceApi->HbsurfaceUuidPut");
            // verify the required parameter 'hbsurface' is set
            if (hbsurface == null)
                throw new ApiException(400, "Missing required parameter 'hbsurface' when calling HoneybeeSurfaceApi->HbsurfaceUuidPut");

            var localVarPath = "/hbsurface/{uuid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", Configuration.ApiClient.ParameterToString(uuid)); // path parameter
            if (hbsurface != null && hbsurface.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(hbsurface); // http body (model) parameter
            }
            else
            {
                localVarPostBody = hbsurface; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfaceUuidPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Modify an existing hbsurface object Modifies any parameter (except uuid) of an hbsurface object by completely replacing the definition object. A finer grain method can be set up later.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <param name="hbsurface">A hbsurface JSON objectr with a uuid key.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task HbsurfaceUuidPutAsync (string uuid, HBSurfaceSchema hbsurface)
        {
             await HbsurfaceUuidPutAsyncWithHttpInfo(uuid, hbsurface);

        }

        /// <summary>
        /// Modify an existing hbsurface object Modifies any parameter (except uuid) of an hbsurface object by completely replacing the definition object. A finer grain method can be set up later.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid">The unique identifier of the hbsurface.</param>
        /// <param name="hbsurface">A hbsurface JSON objectr with a uuid key.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> HbsurfaceUuidPutAsyncWithHttpInfo (string uuid, HBSurfaceSchema hbsurface)
        {
            // verify the required parameter 'uuid' is set
            if (uuid == null)
                throw new ApiException(400, "Missing required parameter 'uuid' when calling HoneybeeSurfaceApi->HbsurfaceUuidPut");
            // verify the required parameter 'hbsurface' is set
            if (hbsurface == null)
                throw new ApiException(400, "Missing required parameter 'hbsurface' when calling HoneybeeSurfaceApi->HbsurfaceUuidPut");

            var localVarPath = "/hbsurface/{uuid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (uuid != null) localVarPathParams.Add("uuid", Configuration.ApiClient.ParameterToString(uuid)); // path parameter
            if (hbsurface != null && hbsurface.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(hbsurface); // http body (model) parameter
            }
            else
            {
                localVarPostBody = hbsurface; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HbsurfaceUuidPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
