# coding: utf-8

"""
    Honeybee Server API

    A sample API definition for a honeybee server  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.material_schema import MaterialSchema  # noqa: E501
from swagger_client.rest import ApiException


class TestMaterialSchema(unittest.TestCase):
    """MaterialSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMaterialSchema(self):
        """Test MaterialSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.material_schema.MaterialSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
