# coding: utf-8

"""
    Honeybee Server API

    A sample API definition for a honeybee server  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.point_in_time_grid_based_schema import PointInTimeGridBasedSchema  # noqa: E501
from swagger_client.rest import ApiException


class TestPointInTimeGridBasedSchema(unittest.TestCase):
    """PointInTimeGridBasedSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointInTimeGridBasedSchema(self):
        """Test PointInTimeGridBasedSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.point_in_time_grid_based_schema.PointInTimeGridBasedSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
