# coding: utf-8

"""
    Honeybee Server API

    A sample API definition for a honeybee server  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.wea_api import WEAApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWEAApi(unittest.TestCase):
    """WEAApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.wea_api.WEAApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_wea_get(self):
        """Test case for wea_get

        Get a list of WEA objects  # noqa: E501
        """
        pass

    def test_wea_post(self):
        """Test case for wea_post

        Create a new wea object  # noqa: E501
        """
        pass

    def test_wea_uuid_delete(self):
        """Test case for wea_uuid_delete

        Delete an existing wea object  # noqa: E501
        """
        pass

    def test_wea_uuid_get(self):
        """Test case for wea_uuid_get

        Get a specific wea object  # noqa: E501
        """
        pass

    def test_wea_uuid_put(self):
        """Test case for wea_uuid_put

        Modify an existing wea object  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
