# coding: utf-8

"""
    Honeybee Server API

    A sample API definition for a honeybee server  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.hoy_schema_hoy import HoySchemaHoy  # noqa: E501
from swagger_client.rest import ApiException


class TestHoySchemaHoy(unittest.TestCase):
    """HoySchemaHoy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHoySchemaHoy(self):
        """Test HoySchemaHoy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.hoy_schema_hoy.HoySchemaHoy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
