# coding: utf-8

"""
    Honeybee Server API

    A sample API definition for a honeybee server  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bsdf_material_api import BSDFMaterialApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBSDFMaterialApi(unittest.TestCase):
    """BSDFMaterialApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.bsdf_material_api.BSDFMaterialApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_material_bsdf_post(self):
        """Test case for material_bsdf_post

        Create a new bsdf material object  # noqa: E501
        """
        pass

    def test_material_bsdf_uuid_put(self):
        """Test case for material_bsdf_uuid_put

        Modify an existing bsdf material file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
