# coding: utf-8

"""
    Honeybee Server API

    A sample API definition for a honeybee server  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.analysis_grid_api import AnalysisGridApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAnalysisGridApi(unittest.TestCase):
    """AnalysisGridApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.analysis_grid_api.AnalysisGridApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analysis_grid_get(self):
        """Test case for analysis_grid_get

        Get a list of analysis_grid objects  # noqa: E501
        """
        pass

    def test_analysis_grid_post(self):
        """Test case for analysis_grid_post

        Create a new analysis_grid file  # noqa: E501
        """
        pass

    def test_analysis_grid_uuid_delete(self):
        """Test case for analysis_grid_uuid_delete

        Delete an existing analysis_grid file  # noqa: E501
        """
        pass

    def test_analysis_grid_uuid_get(self):
        """Test case for analysis_grid_uuid_get

        Get an analysis_grid object  # noqa: E501
        """
        pass

    def test_analysis_grid_uuid_put(self):
        """Test case for analysis_grid_uuid_put

        Modify an existing analysis_grid file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
