# coding: utf-8

"""
    Honeybee Server API

    A sample API definition for a honeybee server  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.translucent_material_schema import TranslucentMaterialSchema  # noqa: E501
from swagger_client.rest import ApiException


class TestTranslucentMaterialSchema(unittest.TestCase):
    """TranslucentMaterialSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranslucentMaterialSchema(self):
        """Test TranslucentMaterialSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.translucent_material_schema.TranslucentMaterialSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
