# coding: utf-8

"""
    Honeybee Server API

    A sample API definition for a honeybee server  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.epw_api import EPWApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEPWApi(unittest.TestCase):
    """EPWApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.epw_api.EPWApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_epw_get(self):
        """Test case for epw_get

        Get a list of EPW objects  # noqa: E501
        """
        pass

    def test_epw_post(self):
        """Test case for epw_post

        Create a new epw file  # noqa: E501
        """
        pass

    def test_epw_uuid_delete(self):
        """Test case for epw_uuid_delete

        Delete an existing epw file  # noqa: E501
        """
        pass

    def test_epw_uuid_get(self):
        """Test case for epw_uuid_get

        Get a specific epw file  # noqa: E501
        """
        pass

    def test_epw_uuid_put(self):
        """Test case for epw_uuid_put

        Modify an existing epw file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
