/* 
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LightSourceMaterialApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LightSourceMaterialApiTests
    {
        private LightSourceMaterialApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LightSourceMaterialApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LightSourceMaterialApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LightSourceMaterialApi
            //Assert.IsInstanceOfType(typeof(LightSourceMaterialApi), instance, "instance is a LightSourceMaterialApi");
        }

        
        /// <summary>
        /// Test MaterialLightSourcePost
        /// </summary>
        [Test]
        public void MaterialLightSourcePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LightSourceMaterialSchema lightSourceMaterial = null;
            //var response = instance.MaterialLightSourcePost(lightSourceMaterial);
            //Assert.IsInstanceOf<InlineResponse204> (response, "response is InlineResponse204");
        }
        
        /// <summary>
        /// Test MaterialLightSourceUuidPut
        /// </summary>
        [Test]
        public void MaterialLightSourceUuidPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //LightSourceMaterialSchema lightSourceMaterial = null;
            //instance.MaterialLightSourceUuidPut(uuid, lightSourceMaterial);
            
        }
        
    }

}
