# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_type import DataType  # noqa: F401,E501
from swagger_server import util


class DataCollection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, header: object=None, data: List[DataType]=None):  # noqa: E501
        """DataCollection - a model defined in Swagger

        :param header: The header of this DataCollection.  # noqa: E501
        :type header: object
        :param data: The data of this DataCollection.  # noqa: E501
        :type data: List[DataType]
        """
        self.swagger_types = {
            'header': object,
            'data': List[DataType]
        }

        self.attribute_map = {
            'header': 'header',
            'data': 'data'
        }

        self._header = header
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'DataCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataCollection of this DataCollection.  # noqa: E501
        :rtype: DataCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def header(self) -> object:
        """Gets the header of this DataCollection.


        :return: The header of this DataCollection.
        :rtype: object
        """
        return self._header

    @header.setter
    def header(self, header: object):
        """Sets the header of this DataCollection.


        :param header: The header of this DataCollection.
        :type header: object
        """

        self._header = header

    @property
    def data(self) -> List[DataType]:
        """Gets the data of this DataCollection.


        :return: The data of this DataCollection.
        :rtype: List[DataType]
        """
        return self._data

    @data.setter
    def data(self, data: List[DataType]):
        """Sets the data of this DataCollection.


        :param data: The data of this DataCollection.
        :type data: List[DataType]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
