# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HoySchemaHoy(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, direct_value: float=None, indirect_value: float=None):  # noqa: E501
        """HoySchemaHoy - a model defined in Swagger

        :param direct_value: The direct_value of this HoySchemaHoy.  # noqa: E501
        :type direct_value: float
        :param indirect_value: The indirect_value of this HoySchemaHoy.  # noqa: E501
        :type indirect_value: float
        """
        self.swagger_types = {
            'direct_value': float,
            'indirect_value': float
        }

        self.attribute_map = {
            'direct_value': 'direct_value',
            'indirect_value': 'indirect_value'
        }

        self._direct_value = direct_value
        self._indirect_value = indirect_value

    @classmethod
    def from_dict(cls, dikt) -> 'HoySchemaHoy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HoySchema_hoy of this HoySchemaHoy.  # noqa: E501
        :rtype: HoySchemaHoy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def direct_value(self) -> float:
        """Gets the direct_value of this HoySchemaHoy.


        :return: The direct_value of this HoySchemaHoy.
        :rtype: float
        """
        return self._direct_value

    @direct_value.setter
    def direct_value(self, direct_value: float):
        """Sets the direct_value of this HoySchemaHoy.


        :param direct_value: The direct_value of this HoySchemaHoy.
        :type direct_value: float
        """

        self._direct_value = direct_value

    @property
    def indirect_value(self) -> float:
        """Gets the indirect_value of this HoySchemaHoy.


        :return: The indirect_value of this HoySchemaHoy.
        :rtype: float
        """
        return self._indirect_value

    @indirect_value.setter
    def indirect_value(self, indirect_value: float):
        """Sets the indirect_value of this HoySchemaHoy.


        :param indirect_value: The indirect_value of this HoySchemaHoy.
        :type indirect_value: float
        """

        self._indirect_value = indirect_value
