# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.wea_schema import WeaSchema  # noqa: F401,E501
from swagger_server import util


class InlineResponse20010(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uuid: str=None, wea: WeaSchema=None):  # noqa: E501
        """InlineResponse20010 - a model defined in Swagger

        :param uuid: The uuid of this InlineResponse20010.  # noqa: E501
        :type uuid: str
        :param wea: The wea of this InlineResponse20010.  # noqa: E501
        :type wea: WeaSchema
        """
        self.swagger_types = {
            'uuid': str,
            'wea': WeaSchema
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'wea': 'wea'
        }

        self._uuid = uuid
        self._wea = wea

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20010':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_10 of this InlineResponse20010.  # noqa: E501
        :rtype: InlineResponse20010
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this InlineResponse20010.


        :return: The uuid of this InlineResponse20010.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this InlineResponse20010.


        :param uuid: The uuid of this InlineResponse20010.
        :type uuid: str
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def wea(self) -> WeaSchema:
        """Gets the wea of this InlineResponse20010.


        :return: The wea of this InlineResponse20010.
        :rtype: WeaSchema
        """
        return self._wea

    @wea.setter
    def wea(self, wea: WeaSchema):
        """Sets the wea of this InlineResponse20010.


        :param wea: The wea of this InlineResponse20010.
        :type wea: WeaSchema
        """
        if wea is None:
            raise ValueError("Invalid value for `wea`, must not be `None`")  # noqa: E501

        self._wea = wea
