# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2004_results import InlineResponse2004Results  # noqa: F401,E501
from swagger_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, results: List[InlineResponse2004Results]=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param results: The results of this InlineResponse2004.  # noqa: E501
        :type results: List[InlineResponse2004Results]
        """
        self.swagger_types = {
            'results': List[InlineResponse2004Results]
        }

        self.attribute_map = {
            'results': 'results'
        }

        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def results(self) -> List[InlineResponse2004Results]:
        """Gets the results of this InlineResponse2004.


        :return: The results of this InlineResponse2004.
        :rtype: List[InlineResponse2004Results]
        """
        return self._results

    @results.setter
    def results(self, results: List[InlineResponse2004Results]):
        """Sets the results of this InlineResponse2004.


        :param results: The results of this InlineResponse2004.
        :type results: List[InlineResponse2004Results]
        """

        self._results = results
