# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.analysis_grid_schema import AnalysisGridSchema  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uuid: str=None, analysis_grid: AnalysisGridSchema=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param uuid: The uuid of this InlineResponse2001.  # noqa: E501
        :type uuid: str
        :param analysis_grid: The analysis_grid of this InlineResponse2001.  # noqa: E501
        :type analysis_grid: AnalysisGridSchema
        """
        self.swagger_types = {
            'uuid': str,
            'analysis_grid': AnalysisGridSchema
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'analysis_grid': 'analysis_grid'
        }

        self._uuid = uuid
        self._analysis_grid = analysis_grid

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this InlineResponse2001.


        :return: The uuid of this InlineResponse2001.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this InlineResponse2001.


        :param uuid: The uuid of this InlineResponse2001.
        :type uuid: str
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def analysis_grid(self) -> AnalysisGridSchema:
        """Gets the analysis_grid of this InlineResponse2001.


        :return: The analysis_grid of this InlineResponse2001.
        :rtype: AnalysisGridSchema
        """
        return self._analysis_grid

    @analysis_grid.setter
    def analysis_grid(self, analysis_grid: AnalysisGridSchema):
        """Sets the analysis_grid of this InlineResponse2001.


        :param analysis_grid: The analysis_grid of this InlineResponse2001.
        :type analysis_grid: AnalysisGridSchema
        """
        if analysis_grid is None:
            raise ValueError("Invalid value for `analysis_grid`, must not be `None`")  # noqa: E501

        self._analysis_grid = analysis_grid
