# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.epw_schema import EpwSchema  # noqa: F401,E501
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uuid: str=None, epw: EpwSchema=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param uuid: The uuid of this InlineResponse2003.  # noqa: E501
        :type uuid: str
        :param epw: The epw of this InlineResponse2003.  # noqa: E501
        :type epw: EpwSchema
        """
        self.swagger_types = {
            'uuid': str,
            'epw': EpwSchema
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'epw': 'epw'
        }

        self._uuid = uuid
        self._epw = epw

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this InlineResponse2003.


        :return: The uuid of this InlineResponse2003.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this InlineResponse2003.


        :param uuid: The uuid of this InlineResponse2003.
        :type uuid: str
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def epw(self) -> EpwSchema:
        """Gets the epw of this InlineResponse2003.


        :return: The epw of this InlineResponse2003.
        :rtype: EpwSchema
        """
        return self._epw

    @epw.setter
    def epw(self, epw: EpwSchema):
        """Sets the epw of this InlineResponse2003.


        :param epw: The epw of this InlineResponse2003.
        :type epw: EpwSchema
        """
        if epw is None:
            raise ValueError("Invalid value for `epw`, must not be `None`")  # noqa: E501

        self._epw = epw
