# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Location(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, city: str=None, latitude: float=None, longitude: float=None, time_zone: str=None, elevation: float=None):  # noqa: E501
        """Location - a model defined in Swagger

        :param city: The city of this Location.  # noqa: E501
        :type city: str
        :param latitude: The latitude of this Location.  # noqa: E501
        :type latitude: float
        :param longitude: The longitude of this Location.  # noqa: E501
        :type longitude: float
        :param time_zone: The time_zone of this Location.  # noqa: E501
        :type time_zone: str
        :param elevation: The elevation of this Location.  # noqa: E501
        :type elevation: float
        """
        self.swagger_types = {
            'city': str,
            'latitude': float,
            'longitude': float,
            'time_zone': str,
            'elevation': float
        }

        self.attribute_map = {
            'city': 'city',
            'latitude': 'latitude',
            'longitude': 'longitude',
            'time_zone': 'time_zone',
            'elevation': 'elevation'
        }

        self._city = city
        self._latitude = latitude
        self._longitude = longitude
        self._time_zone = time_zone
        self._elevation = elevation

    @classmethod
    def from_dict(cls, dikt) -> 'Location':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Location of this Location.  # noqa: E501
        :rtype: Location
        """
        return util.deserialize_model(dikt, cls)

    @property
    def city(self) -> str:
        """Gets the city of this Location.


        :return: The city of this Location.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this Location.


        :param city: The city of this Location.
        :type city: str
        """

        self._city = city

    @property
    def latitude(self) -> float:
        """Gets the latitude of this Location.


        :return: The latitude of this Location.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: float):
        """Sets the latitude of this Location.


        :param latitude: The latitude of this Location.
        :type latitude: float
        """
        if latitude is not None and latitude > 90:  # noqa: E501
            raise ValueError("Invalid value for `latitude`, must be a value less than or equal to `90`")  # noqa: E501
        if latitude is not None and latitude < -90:  # noqa: E501
            raise ValueError("Invalid value for `latitude`, must be a value greater than or equal to `-90`")  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self) -> float:
        """Gets the longitude of this Location.


        :return: The longitude of this Location.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: float):
        """Sets the longitude of this Location.


        :param longitude: The longitude of this Location.
        :type longitude: float
        """
        if longitude is not None and longitude > 180:  # noqa: E501
            raise ValueError("Invalid value for `longitude`, must be a value less than or equal to `180`")  # noqa: E501
        if longitude is not None and longitude < -180:  # noqa: E501
            raise ValueError("Invalid value for `longitude`, must be a value greater than or equal to `-180`")  # noqa: E501

        self._longitude = longitude

    @property
    def time_zone(self) -> str:
        """Gets the time_zone of this Location.


        :return: The time_zone of this Location.
        :rtype: str
        """
        return self._time_zone

    @time_zone.setter
    def time_zone(self, time_zone: str):
        """Sets the time_zone of this Location.


        :param time_zone: The time_zone of this Location.
        :type time_zone: str
        """

        self._time_zone = time_zone

    @property
    def elevation(self) -> float:
        """Gets the elevation of this Location.


        :return: The elevation of this Location.
        :rtype: float
        """
        return self._elevation

    @elevation.setter
    def elevation(self, elevation: float):
        """Sets the elevation of this Location.


        :param elevation: The elevation of this Location.
        :type elevation: float
        """

        self._elevation = elevation
