# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PointSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, x: float=None, y: float=None, z: float=None):  # noqa: E501
        """PointSchema - a model defined in Swagger

        :param x: The x of this PointSchema.  # noqa: E501
        :type x: float
        :param y: The y of this PointSchema.  # noqa: E501
        :type y: float
        :param z: The z of this PointSchema.  # noqa: E501
        :type z: float
        """
        self.swagger_types = {
            'x': float,
            'y': float,
            'z': float
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y',
            'z': 'z'
        }

        self._x = x
        self._y = y
        self._z = z

    @classmethod
    def from_dict(cls, dikt) -> 'PointSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PointSchema of this PointSchema.  # noqa: E501
        :rtype: PointSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> float:
        """Gets the x of this PointSchema.


        :return: The x of this PointSchema.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x: float):
        """Sets the x of this PointSchema.


        :param x: The x of this PointSchema.
        :type x: float
        """

        self._x = x

    @property
    def y(self) -> float:
        """Gets the y of this PointSchema.


        :return: The y of this PointSchema.
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y: float):
        """Sets the y of this PointSchema.


        :param y: The y of this PointSchema.
        :type y: float
        """

        self._y = y

    @property
    def z(self) -> float:
        """Gets the z of this PointSchema.


        :return: The z of this PointSchema.
        :rtype: float
        """
        return self._z

    @z.setter
    def z(self, z: float):
        """Sets the z of this PointSchema.


        :param z: The z of this PointSchema.
        :type z: float
        """

        self._z = z
