# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QueryParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None):  # noqa: E501
        """QueryParameters - a model defined in Swagger

        :param type: The type of this QueryParameters.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'type': str
        }

        self.attribute_map = {
            'type': 'type'
        }

        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'QueryParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryParameters of this QueryParameters.  # noqa: E501
        :rtype: QueryParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this QueryParameters.


        :return: The type of this QueryParameters.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this QueryParameters.


        :param type: The type of this QueryParameters.
        :type type: str
        """

        self._type = type
