/*
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AnalysisSurfaceSchema struct {

	// The name of the surface
	Name string `json:"name,omitempty"`

	// 0.0=Wall, 0.5=UndergroundWall, 1.0=Roof, 1.5=UndergroundCeiling, 2.0=Floor, 2.5=SlabOnGrade, 2.75=ExposedFloor, 3.0=Ceiling, 5.0=Window, 6.0=Context
	SurfaceType float32 `json:"surface_type,omitempty"`

	Vertices []VertexSchema `json:"vertices,omitempty"`

	RadProperties *AnalysisSurfaceSchemaRadProperties `json:"rad_properties,omitempty"`

	SurfaceStates []SurfaceStateSchema `json:"surface_states,omitempty"`
}
