/*
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AnalysisPointSchema struct {

	Location *PointSchema `json:"location,omitempty"`

	Direction *VectorSchema `json:"direction,omitempty"`

	Values []SourceSchema `json:"values,omitempty"`
}
