/*
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GridBasedRecipeSchema struct {

	// The unique identifier of the recipe
	Uuid string `json:"uuid,omitempty"`
}
