/*
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SkyMtxSchema struct {

	Wea *WeaSchema `json:"wea,omitempty"`

	// 1 - Tregenza Sky, 2 - Reinhart Sky, etc. (Default - 1)
	SkyDensity int32 `json:"sky_density,omitempty"`

	// angle in degrees between 0-360 to indicate North
	North float32 `json:"north,omitempty"`

	Hoys *HoyListSchema `json:"hoys,omitempty"`

	// sky mode
	Mode int32 `json:"mode,omitempty"`

	// Suffix for the sky matrix
	Suffix string `json:"suffix,omitempty"`
}
