/*
 * Honeybee Server API
 *
 * A sample API definition for a honeybee server
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VertexSchemaInner struct {

	X float32 `json:"x,omitempty"`

	Y float32 `json:"y,omitempty"`

	Z float32 `json:"z,omitempty"`
}
