/**
 * Honeybee Server API
 * A sample API definition for a honeybee server
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HoneybeeServerApi);
  }
}(this, function(expect, HoneybeeServerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HoneybeeServerApi.AnalysisGridApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnalysisGridApi', function() {
    describe('analysisGridGet', function() {
      it('should call analysisGridGet successfully', function(done) {
        //uncomment below and update the code to test analysisGridGet
        //instance.analysisGridGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('analysisGridPost', function() {
      it('should call analysisGridPost successfully', function(done) {
        //uncomment below and update the code to test analysisGridPost
        //instance.analysisGridPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('analysisGridUuidDelete', function() {
      it('should call analysisGridUuidDelete successfully', function(done) {
        //uncomment below and update the code to test analysisGridUuidDelete
        //instance.analysisGridUuidDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('analysisGridUuidGet', function() {
      it('should call analysisGridUuidGet successfully', function(done) {
        //uncomment below and update the code to test analysisGridUuidGet
        //instance.analysisGridUuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('analysisGridUuidPut', function() {
      it('should call analysisGridUuidPut successfully', function(done) {
        //uncomment below and update the code to test analysisGridUuidPut
        //instance.analysisGridUuidPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
